# Server Configuration
server:
  port: "8080"
  environment: "development"
  read_timeout: 30
  write_timeout: 30

# Logging Configuration
logging:
  level: "info"

# Security Configuration
security:
  jwt_secret: "your-secure-jwt-secret"
  rate_limit: 100
  enable_https: false

# MCP Configuration
mcp:
  # List of known MCP servers (host:port)
  known_servers:
    - "localhost:8081"
    - "localhost:8082"
  
  # Discovery settings
  discovery:
    enabled: true
    interval: "5m"
    timeout: "30s"
  
  # Security settings
  security:
    require_tls: false
    ca_cert: ""
    client_cert: ""
    client_key: ""

# Database Configuration (example)
database:
  host: "localhost"
  port: 5432
  name: "mcp_sentinel"
  user: "postgres"
  password: "postgres"
  sslmode: "disable"

# Cache Configuration (example)
cache:
  enabled: true
  ttl: "15m"
  type: "redis"
  address: "localhost:6379"
  password: ""
  db: 0
